version: '2'
services:
  jenkins:
    image: runmymind/jenkins-docker
    container_name: jenkins
    volumes:
      - /mnt/data/jenkins:/var/jenkins_home
    environment:
      APP_URL: ${APP_URL}
    ports:
      - "8055:8080"
      - "50000:50000"
    restart: always
