version: "2"
services:
  jenkins:
    image: runmymind/jenkins-docker
    container_name: jenkins
    volumes:
      - /mnt/data/jenkins:/var/jenkins_home
    environment:
      - APP_URL=jenkins.example.com
      - VIRTUAL_HOST=jenkins.example.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=jenkins.example.com
      - LETSENCRYPT_EMAIL=mail@example.com
    expose:
      - 8080
    ports:
      - "50000:50000"
    networks: 
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy
